apiVersion: v1
kind: ServiceAccount
metadata:
  name: cracha-gerenciador-pods # Nome intuitivo para o "usuário máquina"
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vinculo-permissao-gerenciador
subjects:
  - kind: ServiceAccount
    name: cracha-gerenciador-pods # Amarra o nosso crachá...
    namespace: default
roleRef:
  kind: ClusterRole
  name: edit # ...à permissão padrão do K8s de "Editar/Criar" coisas no cluster
  apiGroup: rbac.authorization.k8s.io