apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-pv
spec:
  storageClassName: manual # <--- Adicionado aqui
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /dados-residuos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-pvc
spec:
  storageClassName: manual # <--- Adicionado aqui para dar o "match"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi